TicketSystem_Concert/Models/ErrorViewModel.cs
namespace TicketSystem_Concert.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

TicketSystem_Concert/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TicketSystem_Concert.Models;

namespace TicketSystem_Concert.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

TicketSystem_Concert/Controllers/TicketsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TicketSystem_Concert.DAL;
using TicketSystem_Concert.DAL.Entities;

namespace TicketSystem_Concert.Controllers
{
	public class TicketsController : Controller
	{
		private readonly DataBaseContext _context;

		public TicketsController(DataBaseContext context)
		{
			_context = context;
		}

		// GET: Tickets
		public async Task<IActionResult> Index()
		{
			return _context.Tickets != null ?
						View(await _context.Tickets.ToListAsync()) :
						Problem("Entity set 'DataBaseContext.Tickets'  is null.");
		}

		// GET: Tickets/Edit/5
		public async Task<IActionResult> Edit(string? id)
		{
			if (id == null || _context.Tickets == null) return NotFound();

			var ticket = await _context.Tickets.FindAsync(id);

			if (ticket == null) return NotFound();

			return View(ticket);
		}

		// POST: Tickets/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(string id, Ticket ticket)
		{
			if (id != ticket.Id) return NotFound();

			if (ModelState.IsValid)
			{
				try
				{
					ticket.UseData = DateTime.Now;
					ticket.IsUsed = true;
					_context.Update(ticket);
					await _context.SaveChangesAsync();
					return RedirectToAction(nameof(Index));
				}
				catch (DbUpdateException dbUpdateException)
				{
					if (dbUpdateException.InnerException.Message.Contains("duplicate"))
						ModelState.AddModelError(string.Empty, "Ya existe la boleta..");
					else
						ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
				}
				catch (Exception ex)
				{
					ModelState.AddModelError(string.Empty, ex.Message);
				}
			}
			return View(ticket);
		}
	}
}

TicketSystem_Concert/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TicketSystem_Concert/Views/Shared/PartialViews/_TicketCreateEdit.cshtml
@model TicketSystem_Concert.DAL.Entities.Ticket
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="input-group mb-3">
        <label asp-for="Id" class="input-group-text"></label>
        <input asp-for="Id" class="form-control" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="IsUsed" class="input-group-text"></label>
        <select asp-for="IsUsed" class="form-select">
                <option value="false">No</option>
                <option value="true">Si</option>
            <span asp-validation-for="IsUsed" class="text-danger"></span>
        </select>
    </div>
    <br />
    <div class="input-group">
        <label asp-for="EntranceGate" class="input-group-text"></label>
        <select asp-for="EntranceGate" class="form-select">
            <option selected>Seleccione</option>
            <option value="Norte">Norte</option>
            <option value="Sur">Sur</option>
            <option value="Oriental">Oriental</option>
            <option value="Occidental">Occidental</option>
            <span asp-validation-for="EntranceGate" class="text-danger"></span>
        </select>
    </div>


    
    
  

TicketSystem_Concert/Views/Shared/PartialViews/_TicketRegister.cshtml
@model TicketSystem_Concert.DAL.Entities.Ticket
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="input-group mb-3">
        <label asp-for="Id" class="input-group-text"></label>
        <input asp-for="Id" class="form-control" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="IsUsed" class="input-group-text"></label>
        <select asp-for="IsUsed" class="form-select">
                <option value="false">No</option>
                <option value="true">Si</option>
            <span asp-validation-for="IsUsed" class="text-danger"></span>
        </select>
    </div>
    <br />
    <div class="input-group">
        <label asp-for="EntranceGate" class="input-group-text"></label>
        <select asp-for="EntranceGate" class="form-select">
            <option selected>Seleccione</option>
            <option value="Norte">Norte</option>
            <option value="Sur">Sur</option>
            <option value="Oriental">Oriental</option>
            <option value="Occidental">Occidental</option>
            <span asp-validation-for="EntranceGate" class="text-danger"></span>
        </select>
    </div>
    


    
    
  

TicketSystem_Concert/Views/Shared/PartialViews/_TicketRegisterDisable.cshtml
@model TicketSystem_Concert.DAL.Entities.Ticket
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="input-group mb-3">
        <label asp-for="Id" class="input-group-text"></label>
        <input asp-for="Id" class="form-control" disabled/>
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="input-group mb-3">
        <label asp-for="UseData" class="input-group-text"></label>
        <input asp-for="UseData" class="form-control" disabled/>
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="IsUsed" class="input-group-text"></label>
        <select asp-for="IsUsed" class="form-select" disabled>
                <option value="false">No</option>
                <option value="true">Si</option>
            <span asp-validation-for="IsUsed" class="text-danger"></span>
        </select>
    </div>
    <br />
    <div class="input-group">
        <label asp-for="EntranceGate" class="input-group-text"></label>
        <select asp-for="EntranceGate" class="form-select" disabled>
            <option value="Norte">Norte</option>
            <option value="Sur">Sur</option>
            <option value="Oriental">Oriental</option>
            <option value="Occidental">Occidental</option>
            <span asp-validation-for="EntranceGate" class="text-danger"></span>
        </select>
    </div>
    


    
    
  

TicketSystem_Concert/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TicketSystem_Concert</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TicketSystem_Concert.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TicketSystem_Concert</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Concierto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TicketSystem_Concert - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TicketSystem_Concert/Views/Tickets/Edit.cshtml
@model TicketSystem_Concert.DAL.Entities.Ticket

@{
    ViewData["Title"] = "Edit";
}

<h1>Registar</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id" />
            
            @if (Model.IsUsed == false)
            {
                <partial name="../Shared/PartialViews/_TicketRegister" />
                <br />
                <div class="form-group">
                    <input type="submit" value="Registrar" class="btn btn-outline-primary" />
                    <a asp-action="Index" class="btn btn-outline-success">Regresar</a>
                </div>
            }
            else
            {
                <partial name="../Shared/PartialViews/_TicketRegisterDisable" />
                <br />
                <div class="form-group">
                    <a asp-action="Index" class="btn btn-outline-success">Regresar</a>
                </div>
            }
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TicketSystem_Concert/Views/Tickets/Index.cshtml
@model IEnumerable<TicketSystem_Concert.DAL.Entities.Ticket>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
<h1>Concierto</h1>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Bichota</h3>
            </div>
            <div class="panel-body">
                <table class="table table-hover table-responsive table-striped" id="TicketTable">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Id)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var ticket in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => ticket.Id)
                                </td>
                                <td>
                                    <div class="d-grid gap-2 col-8 mx-auto">
                                      <a asp-action="Edit" asp-route-id="@ticket.Id" class="btn btn-outline-warning">Registrar</a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#TicketTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [1],[1]
                ]
            });
        });
    </script>
}